title: Github Profile
author: Liz Hamburger
email: lizhamburger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. I’m Liz, a London based designer who specialises in beautiful websites and wonderful brands.

# social links
twitter_username: @lizhamburger
github_username:  LizHamburger

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
